import numpy as np
a=input("enter the length of the array:")
b= np.array(input("enter the array :"))
c=np.array(input("enter the arrray:"))
print "the det of the matrix:",np.linalg.det(b)
print "the inv of the matrix:",np.linalg.inv(b)
print "the eigen values of the matrix:",np.linalg.eig(b)
print "the singular values of the matrix:",np.linalg.svd(b)
print "the rank of the matrix:",np.rank(b)
print "the meof dian value the matrix:",np.median(b)
print "the maximum of the matrix:",np.max(b)
print "the minimum of the matrix:",np.min(b)
print "the transpose of the matrix:",np.transpose(b)
print "the sum of the matrix:",np.sum(b,c)
print "the substraction of the matrix:",np.subtract(b)
print "the multiplication of the matrix:",np.multiply(b)
print"the sqaure of the matrix :",np.square(b)
print"the zero matrx:",np.zeros((2,2))
print"the ones matrix:",np.ones((1,2))
print"the idintity matrix:",np.eye(2) 
print"the random values matrix:",np.random.random((2,2))

